### ISSUE TITLE
License?

### ISSUE THREAD

**Issue by Enet4** [Enet4/rust-tropes#1]
Which license should I use here?

Most Rust projects choose a dual Apache-2.0 OR MIT license, but this repository is unlikely to have substantial code (except maybe for creating static pages in the future).

**Comment by LukasKalbertodt** [comment]
Seems like CC-WIKI (CC-BY-SA) could be the right license, as this is kind of a wiki. It's the same license as StackOverflow is using. But I'd guess you could also just license it as CC-0. I mean, what is being licensed here? Just the formulation/text, right? Maybe the layout and way to present the information. The information explained here is common knowledge, so not really prone to being licensed. IANAL tho :P

You/We should certainly figure this out before accepting PRs, otherwise adding a license later could be really hard.

**Comment by Enet4** [comment]
That might work. As long as it's simple to apply and doesn't conflict with any static site generator technology in the future, it's gold.

**Comment by Enet4** [comment]
Resolved by #4.
